version: '2.2'
services:
  sftp-arm64v8:
    container_name: sftp-arm64v8
    build:
      context: .
      dockerfile: Dockerfile.aarch64
    image: "chonjay21/sftp:arm64v8-latest"
    ports:
      - "22222:22"
    environment:
      - FORCE_REINIT_CONFIG=false
      - APP_USER_NAME=admin
      - APP_USER_PASSWD=admin
      - APP_UID=1000
      - APP_GID=1000
      - APP_UMASK=007
      - APP_SSHD_PORT=22
      - APP_MOTD_MSG="Welcome!!!"
      - TZ=America/Los_Angeles
    volumes:
      - /sftp/data:/home/sftp/data
      #- /etc/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      #- /etc/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro